-- MySQL Workbench Synchronization
-- Generated: 2015-05-13 08:09
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Kris Vandermast

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


ALTER TABLE `AUDIT_P_towing_be`.`T_INVOICES` 
ADD COLUMN `cd` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `invoice_payment_type`,
ADD COLUMN `cd_by` VARCHAR(255) NOT NULL AFTER `cd`,
ADD COLUMN `ud` TIMESTAMP NULL AFTER `cd_by`,
ADD COLUMN `ud_by` VARCHAR(255) NULL AFTER `ud`;

ALTER TABLE `AUDIT_P_towing_be`.`T_INVOICE_LINES` 
ADD COLUMN `cd` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `item_total_incl_vat`,
ADD COLUMN `cd_by` VARCHAR(255) NOT NULL AFTER `cd`,
ADD COLUMN `ud` TIMESTAMP NULL AFTER `cd_by`,
ADD COLUMN `ud_by` VARCHAR(255) NULL AFTER `ud`,
ADD COLUMN `dd` TIMESTAMP NULL AFTER `ud_by`,
ADD COLUMN `dd_by` VARCHAR(255) NULL AFTER `dd`;

ALTER TABLE `AUDIT_P_towing_be`.`T_INVOICE_CUSTOMERS` 
ADD COLUMN `cd` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `country`,
ADD COLUMN `cd_by` VARCHAR(255) NOT NULL AFTER `cd`,
ADD COLUMN `ud` TIMESTAMP NULL AFTER `cd_by`,
ADD COLUMN `ud_by` VARCHAR(255) NULL AFTER `ud`,
ADD COLUMN `dd` TIMESTAMP NULL AFTER `ud_by`,
ADD COLUMN `dd_by` VARCHAR(255) NULL AFTER `dd`;

ALTER TABLE `AUDIT_P_towing_be`.`T_INVOICES` 
CHANGE COLUMN `invoice_type` `invoice_type` ENUM('CUSTOMER','INSURANCE','COLLECTOR', 'CN') NOT NULL ;

ALTER TABLE `AUDIT_P_towing_be`.`T_INVOICES` 
ADD COLUMN `invoice_ref_id` BIGINT(20) NULL DEFAULT NULL AFTER `document_id`;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
