CREATE TABLE IF NOT EXISTS `T_TOWING_VOUCHER_VALIDATION_MESSAGES` (
  `towing_voucher_id` BIGINT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `message` VARCHAR(512) NOT NULL,
  INDEX `fk_T_TOWING_VOUCHER_VALIDATION_MESSAGES_T_TOWING_VOUCHERS1_idx` (`towing_voucher_id` ASC),
  PRIMARY KEY (`towing_voucher_id`, `code`),
  CONSTRAINT `fk_T_TOWING_VOUCHER_VALIDATION_MESSAGES_T_TOWING_VOUCHERS1`
    FOREIGN KEY (`towing_voucher_id`)
    REFERENCES `T_TOWING_VOUCHERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

