-- MySQL Script generated by MySQL Workbench
-- Thu Oct  2 19:01:06 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -------- -----------------------------------------------------
-- Schema towing
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `towing` ;
CREATE SCHEMA IF NOT EXISTS `towing` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
