-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 11:05:36 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema towing_audit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AUDIT_P_towing_be` ;
CREATE SCHEMA IF NOT EXISTS `AUDIT_P_towing_be` ;
USE `AUDIT_P_towing_be` ;

-- -----------------------------------------------------
-- Table `P_ALLOTMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_ALLOTMENT` ;

CREATE TABLE IF NOT EXISTS `P_ALLOTMENT` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `allotment_agency_id` BIGINT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P_ALLOTMENT_AGENCY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_ALLOTMENT_AGENCY` ;

CREATE TABLE IF NOT EXISTS `P_ALLOTMENT_AGENCY` (
  `id` BIGINT NOT NULL,
  `company_name` VARCHAR(255) NULL,
  `company_vat` VARCHAR(45) NULL,
  `street` VARCHAR(255) NULL,
  `street_number` VARCHAR(45) NULL,
  `street_pobox` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `city` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(45) NOT NULL,
  `ud` TIMESTAMP NULL,
  `ud_by` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P_ALLOTMENT_DIRECTION_INDICATORS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_ALLOTMENT_DIRECTION_INDICATORS` ;

CREATE TABLE IF NOT EXISTS `P_ALLOTMENT_DIRECTION_INDICATORS` (
  `id` INT NOT NULL,
  `allotment_directions_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `lat` DOUBLE NULL,
  `long` DOUBLE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P_ALLOTMENT_DIRECTIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_ALLOTMENT_DIRECTIONS` ;

CREATE TABLE IF NOT EXISTS `P_ALLOTMENT_DIRECTIONS` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P_ALLOTMENT_MAP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_ALLOTMENT_MAP` ;

CREATE TABLE IF NOT EXISTS `P_ALLOTMENT_MAP` (
  `id` BIGINT NOT NULL,
  `allotment_id` INT NOT NULL,
  `direction_id` INT NOT NULL,
  `indicator_id` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P_COMPANY_MODULES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_COMPANY_MODULES` ;

CREATE TABLE IF NOT EXISTS `P_COMPANY_MODULES` (
  `module_id` INT NOT NULL,
  `company_id` BIGINT NOT NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(255) NOT NULL,
  `dd` TIMESTAMP NULL,
  `dd_by` VARCHAR(255) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P_DICTIONARY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_DICTIONARY` ;

CREATE TABLE IF NOT EXISTS `P_DICTIONARY` (
  `id` BIGINT NOT NULL,
  `category` ENUM('COUNTRY_LICENCE_PLATE', 'COLLECTOR', 'TRAFFIC_LANE') NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(255) NULL,
  `ud` TIMESTAMP NULL,
  `ud_by` VARCHAR(255) NULL,
  `dd` TIMESTAMP NULL,
  `dd_by` VARCHAR(255) NULL)
ENGINE = InnoDB;

CREATE INDEX `ix_dictionary_category` ON `P_DICTIONARY` (`category` ASC);


-- -----------------------------------------------------
-- Table `P_HOLIDAYS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_HOLIDAYS` ;

CREATE TABLE IF NOT EXISTS `P_HOLIDAYS` (
  `id` INT NOT NULL,
  `year` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `holiday` DATE NOT NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(255) NOT NULL,
  `ud` TIMESTAMP NULL,
  `ud_by` VARCHAR(255) NULL,
  `dd` TIMESTAMP NULL,
  `dd_by` VARCHAR(255) NULL)
ENGINE = InnoDB;

CREATE INDEX `ix_holiday` ON `P_HOLIDAYS` (`holiday` ASC);


-- -----------------------------------------------------
-- Table `P_INCIDENT_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_INCIDENT_TYPES` ;

CREATE TABLE IF NOT EXISTS `P_INCIDENT_TYPES` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `code_agency` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;

CREATE INDEX `ix_incident_type_code` ON `P_INCIDENT_TYPES` (`code` ASC);

CREATE INDEX `ix_incident_type_code_agency` ON `P_INCIDENT_TYPES` (`code_agency` ASC);


-- -----------------------------------------------------
-- Table `P_MODULE_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_MODULE_ROLES` ;

CREATE TABLE IF NOT EXISTS `P_MODULE_ROLES` (
  `role_id` INT NOT NULL,
  `module_id` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P_MODULES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_MODULES` ;

CREATE TABLE IF NOT EXISTS `P_MODULES` (
  `id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P_POLICE_TRAFFIC_POSTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_POLICE_TRAFFIC_POSTS` ;

CREATE TABLE IF NOT EXISTS `P_POLICE_TRAFFIC_POSTS` (
  `id` INT NOT NULL,
  `allotment_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_ROLES` ;

CREATE TABLE IF NOT EXISTS `P_ROLES` (
  `id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `dd` TIMESTAMP NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P_TIMEFRAME_ACTIVITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_TIMEFRAME_ACTIVITIES` ;

CREATE TABLE IF NOT EXISTS `P_TIMEFRAME_ACTIVITIES` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `default_value` DECIMAL(10,0) NULL,
  `is_modifiable` TINYINT(1) NULL)
ENGINE = InnoDB;

CREATE INDEX `ix_timeframe_activities_code` ON `P_TIMEFRAME_ACTIVITIES` (`code` ASC);


-- -----------------------------------------------------
-- Table `P_TIMEFRAME_ACTIVITY_FEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_TIMEFRAME_ACTIVITY_FEE` ;

CREATE TABLE IF NOT EXISTS `P_TIMEFRAME_ACTIVITY_FEE` (
  `id` INT NOT NULL,
  `timeframe_id` INT NOT NULL,
  `timeframe_activity_id` INT NOT NULL,
  `fee_excl_vat` DOUBLE NOT NULL,
  `fee_incl_vat` DOUBLE NOT NULL,
  `valid_from` DATETIME NOT NULL,
  `valid_until` DATETIME NULL)
ENGINE = InnoDB;

CREATE INDEX `ix_timeframe_activity_fee_valid_from` ON `P_TIMEFRAME_ACTIVITY_FEE` (`valid_from` ASC);

CREATE INDEX `ix_timeframe_activity_fee_valid_until` ON `P_TIMEFRAME_ACTIVITY_FEE` (`valid_until` ASC);


-- -----------------------------------------------------
-- Table `P_TIMEFRAMES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_TIMEFRAMES` ;

CREATE TABLE IF NOT EXISTS `P_TIMEFRAMES` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P_TIMEFRAME_VALIDITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P_TIMEFRAME_VALIDITY` ;

CREATE TABLE IF NOT EXISTS `P_TIMEFRAME_VALIDITY` (
  `id` INT NOT NULL,
  `timeframe_id` INT NOT NULL,
  `category` ENUM('WORKDAY', 'SATURDAY', 'SUNDAY', 'HOLIDAY') NOT NULL,
  `from` TIME NOT NULL,
  `till` TIME NOT NULL)
ENGINE = InnoDB;

CREATE INDEX `ix_tf_validity_from` ON `P_TIMEFRAME_VALIDITY` (`from` ASC);

CREATE INDEX `ix_tf_validity_till` ON `P_TIMEFRAME_VALIDITY` (`till` ASC);


-- -----------------------------------------------------
-- Table `T_COMPANIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_COMPANIES` ;

CREATE TABLE IF NOT EXISTS `T_COMPANIES` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `street_number` VARCHAR(45) NULL,
  `street_pobox` VARCHAR(45) NULL,
  `zip` VARCHAR(4) NULL,
  `city` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `website` VARCHAR(255) NULL,
  `vat` VARCHAR(45) NULL,
  `mobile_device_id` VARCHAR(255) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_COMPANY_ALLOTMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_COMPANY_ALLOTMENTS` ;

CREATE TABLE IF NOT EXISTS `T_COMPANY_ALLOTMENTS` (
  `company_id` BIGINT NOT NULL,
  `allotment_id` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_COMPANY_BANK_ACCOUNT_NUMBERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_COMPANY_BANK_ACCOUNT_NUMBERS` ;

CREATE TABLE IF NOT EXISTS `T_COMPANY_BANK_ACCOUNT_NUMBERS` (
  `id` BIGINT NOT NULL,
  `company_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `bic` VARCHAR(45) NOT NULL,
  `iban` VARCHAR(255) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_COMPANY_DEPOTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_COMPANY_DEPOTS` ;

CREATE TABLE IF NOT EXISTS `T_COMPANY_DEPOTS` (
  `id` BIGINT NOT NULL,
  `company_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `street` VARCHAR(255) NULL,
  `street_number` VARCHAR(45) NULL,
  `street_pobox` VARCHAR(45) NULL,
  `zip` VARCHAR(4) NULL,
  `city` VARCHAR(255) NULL,
  CONSTRAINT `fk_T_COMPANY_DEPOT_T_COMPANIES1`
    FOREIGN KEY (`company_id`)
    REFERENCES `towing`.`T_COMPANIES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_T_COMPANY_DEPOT_T_COMPANIES1_idx` ON `T_COMPANY_DEPOTS` (`company_id` ASC);


-- -----------------------------------------------------
-- Table `T_COMPANY_VEHICLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_COMPANY_VEHICLES` ;

CREATE TABLE IF NOT EXISTS `T_COMPANY_VEHICLES` (
  `id` BIGINT NOT NULL,
  `company_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `licence_plate` VARCHAR(45) NOT NULL,
  `type` ENUM('SIGNA', 'TOWING', 'CRANE', 'TRUCK', 'COLLISION') NOT NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(255) NOT NULL,
  `ud` TIMESTAMP NULL,
  `ud_by` VARCHAR(255) NULL,
  `dd` TIMESTAMP NULL,
  `dd_by` VARCHAR(255) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_DOCUMENT_BLOB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_DOCUMENT_BLOB` ;

CREATE TABLE IF NOT EXISTS `T_DOCUMENT_BLOB` (
  `id` BIGINT NOT NULL,
  `content` LONGTEXT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_DOCUMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_DOCUMENTS` ;

CREATE TABLE IF NOT EXISTS `T_DOCUMENTS` (
  `id` BIGINT NOT NULL,
  `document_blob_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `content_type` VARCHAR(255) NOT NULL,
  `file_size` BIGINT NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(255) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_DOSSIER_COMM_ATTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_DOSSIER_COMM_ATTS` ;

CREATE TABLE IF NOT EXISTS `T_DOSSIER_COMM_ATTS` (
  `id` BIGINT NOT NULL,
  `dossier_communication_id` BIGINT NOT NULL,
  `document_id` BIGINT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_DOSSIER_COMMUNICATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_DOSSIER_COMMUNICATIONS` ;

CREATE TABLE IF NOT EXISTS `T_DOSSIER_COMMUNICATIONS` (
  `id` BIGINT NOT NULL,
  `dossier_id` BIGINT NOT NULL,
  `towing_voucher_id` BIGINT NULL,
  `type` ENUM('INTERNAL', 'EMAIL') NOT NULL,
  `subject` VARCHAR(255) NULL,
  `message` LONGTEXT NOT NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(255) NOT NULL)
ENGINE = InnoDB;

CREATE INDEX `ix_dossier_comm_type` ON `T_DOSSIER_COMMUNICATIONS` (`type` ASC);


-- -----------------------------------------------------
-- Table `T_DOSSIERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_DOSSIERS` ;

CREATE TABLE IF NOT EXISTS `T_DOSSIERS` (
  `id` BIGINT NOT NULL,
  `timeframe_id` INT NOT NULL,
  `company_id` BIGINT NULL,
  `police_traffic_post_id` INT NULL,
  `incident_type_id` INT NULL,
  `allotment_id` INT NULL,
  `allotment_direction_indicator_id` INT NULL,
  `allotment_direction_id` INT NULL,
  `dossier_number` INT(6) ZEROFILL NOT NULL,
  `call_date` DATETIME NULL,
  `call_date_is_holiday` TINYINT(1) NULL,
  `call_number` VARCHAR(45) NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(255) NOT NULL,
  `ud` TIMESTAMP NULL,
  `ud_by` VARCHAR(255) NULL)
ENGINE = InnoDB;

CREATE INDEX `ix_dossier_dossier_number` ON `T_DOSSIERS` (`dossier_number` ASC);

CREATE INDEX `ix_dossier_call_number` ON `T_DOSSIERS` (`call_number` ASC);

CREATE INDEX `ix_dossier_call_date` ON `T_DOSSIERS` (`call_date` ASC);


-- -----------------------------------------------------
-- Table `T_INCIDENT_TRAFFIC_LANES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_INCIDENT_TRAFFIC_LANES` ;

CREATE TABLE IF NOT EXISTS `T_INCIDENT_TRAFFIC_LANES` (
  `id` BIGINT NOT NULL,
  `dossier_id` BIGINT NOT NULL,
  `traffic_lane_id` BIGINT NOT NULL)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `T_INSURANCES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_INSURANCES` ;

CREATE TABLE IF NOT EXISTS `T_INSURANCES` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `vat` VARCHAR(45) NOT NULL,
  `street` VARCHAR(255) NULL,
  `street_number` VARCHAR(45) NULL,
  `street_pobox` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `city` VARCHAR(255) NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(45) NOT NULL,
  `ud` TIMESTAMP NULL,
  `ud_by` VARCHAR(45) NULL,
  `dd` TIMESTAMP NULL,
  `dd_by` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_RECIPIENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_RECIPIENTS` ;

CREATE TABLE IF NOT EXISTS `T_RECIPIENTS` (
  `id` BIGINT NOT NULL,
  `dossier_communication_id` BIGINT NOT NULL,
  `type` ENUM('TO', 'CC', 'BCC') NOT NULL,
  `email_address` VARCHAR(255) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_TOWING_ACTIVITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_TOWING_ACTIVITIES` ;

CREATE TABLE IF NOT EXISTS `T_TOWING_ACTIVITIES` (
  `towing_voucher_id` BIGINT NOT NULL,
  `activity_id` INT NOT NULL,
  `amount` DOUBLE NOT NULL,
  `cal_fee_excl_vat` DOUBLE NOT NULL,
  `cal_fee_incl_vat` DOUBLE NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_TOWING_CUSTOMERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_TOWING_CUSTOMERS` ;

CREATE TABLE IF NOT EXISTS `T_TOWING_CUSTOMERS` (
  `id` BIGINT NOT NULL,
  `voucher_id` BIGINT NOT NULL,
  `type` ENUM('DEFAULT', 'AGENCY') NOT NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `company_name` VARCHAR(255) NULL,
  `company_vat` VARCHAR(45) NULL,
  `company_vat_foreign_country` TINYINT(1) NULL,
  `street` VARCHAR(255) NULL,
  `street_number` VARCHAR(45) NULL,
  `street_pobox` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `city` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `invoice_ref` VARCHAR(255) NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(45) NOT NULL,
  `ud` TIMESTAMP NULL,
  `ud_by` VARCHAR(45) NULL)
ENGINE = InnoDB;

CREATE INDEX `ix_towing_customers_first_name` ON `T_TOWING_CUSTOMERS` (`first_name` ASC);

CREATE INDEX `ix_towing_customers_last_name` ON `T_TOWING_CUSTOMERS` (`last_name` ASC);

CREATE INDEX `ix_towing_customers_company` ON `T_TOWING_CUSTOMERS` (`company_name` ASC);


-- -----------------------------------------------------
-- Table `T_TOWING_DEPOTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_TOWING_DEPOTS` ;

CREATE TABLE IF NOT EXISTS `T_TOWING_DEPOTS` (
  `id` BIGINT NOT NULL,
  `voucher_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NULL,
  `street` VARCHAR(255) NULL,
  `street_number` VARCHAR(45) NULL,
  `street_pobox` VARCHAR(45) NULL,
  `zip` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `default_depot` TINYINT(1) NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(45) NOT NULL,
  `ud` TIMESTAMP NULL,
  `ud_by` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_TOWING_INCIDENT_CAUSERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_TOWING_INCIDENT_CAUSERS` ;

CREATE TABLE IF NOT EXISTS `T_TOWING_INCIDENT_CAUSERS` (
  `id` BIGINT NOT NULL,
  `voucher_id` BIGINT NOT NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `company_name` VARCHAR(255) NULL,
  `company_vat` VARCHAR(45) NULL,
  `company_vat_foreign_country` TINYINT(1) NULL,
  `street` VARCHAR(255) NULL,
  `street_number` VARCHAR(45) NULL,
  `street_pobox` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `city` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(45) NOT NULL,
  `ud` VARCHAR(45) NULL,
  `ud_by` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_TOWING_VOUCHER_ATTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_TOWING_VOUCHER_ATTS` ;

CREATE TABLE IF NOT EXISTS `T_TOWING_VOUCHER_ATTS` (
  `id` BIGINT NOT NULL,
  `towing_voucher_id` BIGINT NOT NULL,
  `document_id` BIGINT NOT NULL,
  `category` ENUM('SIGNATURE_COLLECTOR', 'SIGNATURE_POLICE', 'SIGNATURE_CAUSER', 'ASSISTANCE_ATT', 'VEHICLE_DAMAGE', 'ATT') NOT NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(255) NOT NULL,
  `dd` TIMESTAMP NULL,
  `dd_by` VARCHAR(255) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_TOWING_VOUCHER_PAYMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_TOWING_VOUCHER_PAYMENTS` ;

CREATE TABLE IF NOT EXISTS `T_TOWING_VOUCHER_PAYMENTS` (
  `id` BIGINT NOT NULL,
  `towing_voucher_id` BIGINT NOT NULL,
  `amount_guaranteed_by_insurance` DOUBLE NULL,
  `amount_customer` DOUBLE NULL,
  `paid_in_cash` DOUBLE NULL,
  `paid_by_bank_deposit` DOUBLE NULL,
  `paid_by_debit_card` DOUBLE NULL,
  `paid_by_credit_card` DOUBLE NULL,
  `cal_amount_paid` DOUBLE NULL,
  `cal_amount_unpaid` DOUBLE NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(45) NOT NULL,
  `ud` TIMESTAMP NULL,
  `ud_by` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_TOWING_VOUCHERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_TOWING_VOUCHERS` ;

CREATE TABLE IF NOT EXISTS `T_TOWING_VOUCHERS` (
  `id` BIGINT NOT NULL,
  `dossier_id` BIGINT NOT NULL,
  `collector_id` BIGINT NULL,
  `insurance_id` BIGINT NULL,
  `voucher_number` INT(6) ZEROFILL NULL,
  `status` ENUM('NEW', 'IN PROGRESS', 'COMPLETED', 'TO CHECK', 'AGENCY', 'READY FOR INVOICE', 'INVOICED', 'CLOSED') NOT NULL,
  `police_signature_dt` DATETIME NULL,
  `recipient_signature_dt` DATETIME NULL,
  `insurance_dossiernr` VARCHAR(45) NULL,
  `insurance_warranty_held_by` VARCHAR(255) NULL,
  `vehicule` VARCHAR(255) NULL,
  `vehicule_type` VARCHAR(255) NULL,
  `vehicule_color` VARCHAR(255) NULL,
  `vehicule_keys_present` TINYINT(1) NULL,
  `vehicule_licenceplate` VARCHAR(15) NULL,
  `vehicule_country` VARCHAR(5) NULL,
  `vehicule_collected` DATETIME NULL,
  `vehicule_impact_remarks` TEXT NULL,
  `towing_id` VARCHAR(36) NULL,
  `towed_by` VARCHAR(45) NULL,
  `towed_by_vehicle` VARCHAR(15) NULL,
  `towing_vehicle_id` BIGINT NULL,
  `towing_called` DATETIME NULL,
  `towing_arrival` DATETIME NULL,
  `towing_start` DATETIME NULL,
  `towing_completed` DATETIME NULL,
  `signa_id` VARCHAR(36) NULL,
  `signa_by` VARCHAR(45) NULL,
  `signa_by_vehicle` VARCHAR(15) NULL,
  `signa_arrival` DATETIME NULL,
  `cic` DATETIME NULL,
  `additional_info` TEXT NULL,
  `cd` TIMESTAMP NOT NULL,
  `cd_by` VARCHAR(255) NOT NULL,
  `ud` TIMESTAMP NULL,
  `ud_by` VARCHAR(255) NULL)
ENGINE = InnoDB;

CREATE INDEX `ix_towing_voucher_number` ON `T_TOWING_VOUCHERS` (`voucher_number` ASC);

CREATE INDEX `ix_towing_voucher_status` ON `T_TOWING_VOUCHERS` (`status` ASC);

CREATE INDEX `ix_towing_voucher_vehicle_collected` ON `T_TOWING_VOUCHERS` (`vehicule_collected` ASC);

CREATE INDEX `ix_towing_voucher_vehicle` ON `T_TOWING_VOUCHERS` (`vehicule` ASC);

CREATE INDEX `ix_towing_voucher_vehicle_type` ON `T_TOWING_VOUCHERS` (`vehicule_type` ASC);

CREATE INDEX `ix_towing_voucher_vehicle_licence_plate` ON `T_TOWING_VOUCHERS` (`vehicule_licenceplate` ASC);


-- -----------------------------------------------------
-- Table `T_USER_PASSWORDS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_USER_PASSWORDS` ;

CREATE TABLE IF NOT EXISTS `T_USER_PASSWORDS` (
  `id` BIGINT NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `pwd` VARCHAR(255) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_USER_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_USER_ROLES` ;

CREATE TABLE IF NOT EXISTS `T_USER_ROLES` (
  `role_id` INT NOT NULL,
  `user_id` VARCHAR(36) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_USERS` ;

CREATE TABLE IF NOT EXISTS `T_USERS` (
  `id` VARCHAR(36) NOT NULL,
  `company_id` BIGINT NOT NULL,
  `vehicle_id` BIGINT NULL,
  `signature_document_id` BIGINT NULL,
  `login` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `is_signa` TINYINT(1) NULL,
  `is_towing` TINYINT(1) NULL,
  `mobile_device_id` VARCHAR(255) NULL,
  `is_active` TINYINT(1) NOT NULL,
  `login_attempts` TINYINT NULL,
  `is_locked` TINYINT(1) NOT NULL,
  `locked_ts` TIMESTAMP NULL,
  `cd` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cd_by` VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
  `ud` TIMESTAMP NULL,
  `ud_by` VARCHAR(255) NULL,
  `dd` TIMESTAMP NULL,
  `dd_by` VARCHAR(255) NULL)
ENGINE = InnoDB;

CREATE INDEX `ix_users_login` ON `T_USERS` (`login` ASC);


-- -----------------------------------------------------
-- Table `T_USER_TOKENS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_USER_TOKENS` ;

CREATE TABLE IF NOT EXISTS `T_USER_TOKENS` (
  `user_id` VARCHAR(36) NOT NULL,
  `token` VARCHAR(255) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
